# 帮助菜单配置
help_menu:
  title: "maimai-plugin 帮助菜单"
  sections:
    - title: "基础功能"
      commands:
        - cmd: "#mai help"
          desc: "显示帮助菜单"
        - cmd: "#mai info"
          desc: "查看个人信息"
        - cmd: "#mai bind"
          desc: "绑定好友码"
        - cmd: "#mai unbind"
          desc: "解绑好友码"
    
    - title: "查分功能"
      commands:
        - cmd: "#mai b50"
          desc: "查看B50成绩"
        - cmd: "#mai recent"
          desc: "查看最近游玩记录"
        - cmd: "#mai score"
          desc: "查询单曲成绩"
        - cmd: "#mai search"
          desc: "搜索歌曲(支持难度、等级等)"
        - cmd: "#mai random"
          desc: "随机一首歌"
        - cmd: "#mai plate"
          desc: "查看名牌进度"
        - cmd: "#mai rank"
          desc: "查看排行榜"
    
    - title: "管理功能"
      commands:
        - cmd: "#mai 更新"
          desc: "更新插件"
        - cmd: "#mai 设置"
          desc: "修改插件设置"
        - cmd: "#mai 封禁"
          desc: "封禁用户使用权限"
        - cmd: "#mai 解封"
          desc: "解除用户封禁"

note: "注：以上指令中的mai也可以使用maimai" 