title: "maimai-plugin 帮助菜单"
groups:
  - groupTitle: "基础功能"
    commands:
      - command: "#mai help"
        description: "显示帮助菜单"
      - command: "#mai info" 
        description: "查看个人信息"
      - command: "#mai bind"
        description: "绑定好友码"
      - command: "#mai unbind"
        description: "解绑好友码"
  - groupTitle: "查分功能"
    commands:
      - command: "#mai b50"
        description: "查看B50成绩"
      - command: "#mai recent"
        description: "查看最近游玩记录"
      - command: "#mai score"
        description: "查询单曲成绩"
      - command: "#mai search ID"
        description: "搜索(支持音频、头像、曲绘、名牌、姓名框)"
      - command: "#mai random"
        description: "随机一首歌(支持难度、等级等)"
      - command: "#mai plate"
        description: "查看名牌进度"
      - command: "#mai rank"
        description: "查看排行榜"
  - groupTitle: "管理功能"
    commands:
      - command: "#mai updata"
        description: "更新插件"
      - command: "#mai 设置"
        description: "修改插件设置"
      - command: "#mai deleass"
        description: "清除临时数据"
footer: "Powered by maimai-plugin"
