title: "maimai-plugin 帮助菜单"
groups:
  - groupTitle: "基础功能"
    commands:
      - command: "#mai help"
        description: "显示帮助菜单"
      - command: "#mai info @好友" 
        description: "查看个人信息"
      - command: "#mai bind"
        description: "绑定好友码"
      - command: "#mai unbind"
        description: "解绑好友码"
  - groupTitle: "查分功能"
    commands:
      - command: "类型支持<歌曲|姓名框|头像|背景框|收藏品|曲绘>"
        description: "名称支持别名搜索"
      - command: "#mai b50<@好友>"
        description: "查看B50成绩"
      - command: "#mai recent<@好友>"
        description: "查看最近游玩记录"
      - command: "#mai score<名称><@好友>"
        description: "查询单曲成绩"
      - command: "#mai search<类型><名称>"
        description: "支持模糊搜索"
      - command: "#mai up"
        description: "上传刚刚搜索到的资源文件"
      - command: "#mai random<类型><难度>"
        description: "随机各种资源"
      - command: "#mai guess <类型>"
        description: "猜谜游戏支持猜图、猜音乐"
      - command: "#mai plate"
        description: "查看名牌进度"
      - command: "#mai rank"
        description: "查看排行榜"
  - groupTitle: "管理功能"
    commands:
      - command: "#mai updata"
        description: "更新插件"
      - command: "#mai 设置"
        description: "修改插件设置"
      - command: "#mai deleass"
        description: "清除临时数据"
      - command: "#mai reset"
        description: "重置插件配置"
footer: "Powered by maimai-plugin"

